### ISSUE TITLE
为什么我下载源码，安装依赖后，根据readMe的操作步骤会报错呢?

### ISSUE THREAD

**Issue by Niqian** [aisuda/amis-widget-cli#9]
XXXXXX\node_modules\rollup-plugin-node-externals\dist\cjs\index.js:45
            const pkg = JSON.parse((await fs.promises.readFile(packagePath)).toS
tring()) ?? {};

          ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\suning\platspringBoot\baseproject\amis-editor-vue-
snbsdk\node_modules\akfun\src\config\rollup.config.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

node版本也是符合要求的，v12.22.10。手动修改报错的js，把??去掉可以启动成功。

**Comment by wibetter** [comment]
请问你下载的是哪个组件模板？

**Comment by Niqian** [comment]
> 
使用的是这个模板 vue的
[vue-custom-widget-template](https://github.com/aisuda/vue-custom-widget-template)

**Comment by wibetter** [comment]
请问执行到哪一步报错了？

**Comment by Niqian** [comment]
> 请问执行到哪一步报错了？

直接amis dev就报错了啊

**Comment by Niqian** [comment]
> 请问执行到哪一步报错了？
您看下您那边是没有没有提交版本锁定文件，您可以试下把node_modules删除重新下载，看看有没有相同的错误

**Comment by wibetter** [comment]
我这边删除node_modules和package-lock.json重新安装后执行 npm run dev 可以正常运行。npm list akfun看一下用到的是哪个版本，初步怀疑您用到的akfun的版本不对（可能是vue3版）。目前已经在amis-widget-cli中固定了构建工具的依赖版本，可以重新安装一下amis-widget-cli：npm install -g amis-widget-cli。
